name: RPM Build
on: push

jobs:
  build_tarball:
    name: Builds .tar file
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Replace version in grc.spec so correct source is downloaded when building RPM
        run: sed -Ei 's/(^Version:[[:space:]]*).*/\1${{github.ref_name}}/' grc.spec

      - name: Confirm version in grc.spec
        run: head -n 2 grc.spec

      - name: Create archive
        run: tar -cvf grc-${{github.ref_name}}.tar.gz *

      - name: Upload .tar.gz archive as artifact
        uses: actions/upload-artifact@v3
        with:
          name: grc-${{github.ref_name}}.tar.gz
          path: grc-${{github.ref_name}}.tar.gz          

  build_rpm:
    name: build RPM
    needs: build_tarball
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: RPM Build
        id: rpm
        uses: naveenrajm7/rpmbuild@master
        with:
          spec_file: grc.spec
        
      - name: Upload RPM archive as artifact
        uses: actions/upload-artifact@v3
        with:
          name: rpm
          path: rpmbuild/RPMS/*/grc*x86_64.rpm

  build_deb:
    name: Build DEB
    needs: build_rpm
    runs-on: ubuntu-latest
    steps:
      - name: Download RPM artifact
        uses: actions/download-artifact@v1.0.0
        with:
          name: rpm

      - name: Convert RPM to DEB
        run: |
          sudo apt install -y alien
          sudo alien --to-deb rpm/grc-${{github.ref_name}}-1.el7.x86_64.rpm

      - name: Upload artifact DEB
        uses: actions/upload-artifact@v1.0.0
        with:
          name: grc_${{github.ref_name}}-1.x86_64.deb
          path: grc_*.deb
