name: Main

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  # build-archive:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #       
  #     - name: Tar
  #       run: tar -cvf grc-${{github.ref_name}}.tar.gz *

  #     - name: Upload .tar.gz Archive as Artifact
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: grc-${{github.ref_name}}.tar.gz
  #         path: grc-${{github.ref_name}}.tar.gz
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: build RPM package
      id: rpm
      uses: naveenrajm7/rpmbuild@master
      with:
        spec_file: "grc.spec"

    - name: Upload artifact RPM
      uses: actions/upload-artifact@v1.0.0
      with:
        name: grc-${github.ref_name}.el8.x86_64.rpm
        path: ${{ steps.rpm.outputs.rpm_dir_path }}/**/grc-*.rpm

    - name: Convert RPM to DEB
      run: |
        apt install -y alien
        alien --to-deb ${{ steps.rpm.outputs.rpm_dir_path }}/**/grc-*.rpm

    - name: Upload artifact DEB
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Binary RPM
        path: ./**/*.deb

    - name: Release       
      uses: softprops/action-gh-release@v1        
      with:          
        files: |
          #grc-${{github.ref_name}}.tar.gz   
          ./**/grc-*.rpm
          ./**/grc_*.deb
